// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	crawler "github.com/moonsub-kim/crawl-data-slack/internal/pkg/crawler"
	mock "github.com/stretchr/testify/mock"
	cli "github.com/urfave/cli/v2"

	zap "go.uber.org/zap"
)

// initCrawlerFunc is an autogenerated mock type for the initCrawlerFunc type
type initCrawlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, logger, channel
func (_m *initCrawlerFunc) Execute(ctx *cli.Context, logger *zap.Logger, channel string) (crawler.Crawler, error) {
	ret := _m.Called(ctx, logger, channel)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 crawler.Crawler
	var r1 error
	if rf, ok := ret.Get(0).(func(*cli.Context, *zap.Logger, string) (crawler.Crawler, error)); ok {
		return rf(ctx, logger, channel)
	}
	if rf, ok := ret.Get(0).(func(*cli.Context, *zap.Logger, string) crawler.Crawler); ok {
		r0 = rf(ctx, logger, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crawler.Crawler)
		}
	}

	if rf, ok := ret.Get(1).(func(*cli.Context, *zap.Logger, string) error); ok {
		r1 = rf(ctx, logger, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newInitCrawlerFunc creates a new instance of initCrawlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newInitCrawlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *initCrawlerFunc {
	mock := &initCrawlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
