version: '3.8'

services:
  app:
    container_name: crawl-data-slack
    build:
      context: .
      target: build
    command: bash -c "sleep 1 && echo ${COMMAND} && /go/bin/crawl-data-slack ${COMMAND}"
    environment:
      - GROUPWARE_ID=${GROUPWARE_ID}
      - GROUPWARE_PW=${GROUPWARE_PW}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - MYSQL_CONN=root@tcp(db:3306)/crawler?parseTime=true&charset=utf8
    volumes:
      - ./driver:/app/driver/
    depends_on:
     - db

  db:
    image: mysql:8.0
    restart: always
    ports: 
      - 3306:3306
    environment:
     - MYSQL_DATABASE=crawler
     - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: