version: '3.8'

services:
  app:
    container_name: crawl-data-slack
    build:
      context: .
      target: prod
    command:
      - bash
      - -c
      - |
        wait-for-it.sh postgres:5432 -t 60 -- crawl-data-slack ${COMMAND}
      # crawl groupware -job declined_payments
    environment:
      - IS_DEBUG=${IS_DEBUG}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GROUPWARE_ID=${GROUPWARE_ID}
      - GROUPWARE_PW=${GROUPWARE_PW}
      - EOMISAE_ID=${EOMISAE_ID}
      - EOMISAE_PW=${EOMISAE_PW}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - MYSQL_CONN=${MYSQL_CONN:-root@tcp(db:3306)/crawler?parseTime=true&charset=utf8}
      - POSTGRES_CONN=${POSTGRES_CONN:-host=postgres user=crawler password=crawler dbname=crawler port=5432 sslmode=disable}
      - CHROME_HOST=chrome:9222
      # - CHROME_LOG_LEVEL=DEBUG
    depends_on:
    #  - db
    #  - chrome
     - postgres

  chrome:
    container_name: chrome
    image: chromedp/headless-shell:stable
    command: "--disable-dev-shm-usage"
    ports:
      - "9222:9222"

  # db:
  #   container_name: db
  #   platform: linux/x86_64
  #   image: mysql:8.0.26
  #   restart: always
  #   ports: 
  #     - 3306:3306
  #   environment:
  #    - MYSQL_DATABASE=crawler
  #    - MYSQL_USER=crawler
  #    - MYSQL_PASSWORD=crawler
  #    - MYSQL_ALLOW_EMPTY_PASSWORD=1
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  postgres:
    container_name: cralwer-postgres
    image: "postgres:10.6"
    environment:
      - POSTGRES_USER=crawler
      - POSTGRES_PASSWORD=crawler
      - POSTGRES_DB=crawler
    ports:
      - "5432:5432"

volumes:
  mysql_data:
