version: '3.8'

services:
  app:
    container_name: crawl-data-slack
    build:
      context: .
      target: prod
    command:
      - bash
      - -c
      - |
        /bin/wait-for-it.sh chrome:9222 -t 60 -- /go/bin/crawl-data-slack ${COMMAND}
      # crawl groupware -job declined_payments
    environment:
      - GROUPWARE_ID=${GROUPWARE_ID}
      - GROUPWARE_PW=${GROUPWARE_PW}
      - EOMISAE_ID=${EOMISAE_ID}
      - EOMISAE_PW=${EOMISAE_PW}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - MYSQL_CONN=${MYSQL_CONN:-root@tcp(db:3306)/crawler?parseTime=true&charset=utf8}
      - CHROME_HOST=chrome:9222
      # - CHROME_LOG_LEVEL=DEBUG
    volumes:
      - ./data/:/app/data/
    depends_on:
     - db
     - chrome

  chrome:
    container_name: chrome
    image: chromedp/headless-shell:stable
    command: "--disable-dev-shm-usage"
    ports:
      - "9222:9222"

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    ports: 
      - 3306:3306
    environment:
     - MYSQL_DATABASE=crawler
     - MYSQL_USER=crawler
     - MYSQL_PASSWORD=crawler
     - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
