// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	rss "github.com/moonsub-kim/crawl-data-slack/internal/pkg/rss"
	mock "github.com/stretchr/testify/mock"
)

// CrawlerOption is an autogenerated mock type for the CrawlerOption type
type CrawlerOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CrawlerOption) Execute(_a0 *rss.Crawler) {
	_m.Called(_a0)
}

// NewCrawlerOption creates a new instance of CrawlerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCrawlerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *CrawlerOption {
	mock := &CrawlerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
