// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	crawler "github.com/moonsub-kim/crawl-data-slack/internal/pkg/crawler"
	mock "github.com/stretchr/testify/mock"
)

// Crawler is an autogenerated mock type for the Crawler type
type Crawler struct {
	mock.Mock
}

// Crawl provides a mock function with no fields
func (_m *Crawler) Crawl() ([]crawler.Event, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Crawl")
	}

	var r0 []crawler.Event
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]crawler.Event, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []crawler.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]crawler.Event)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCrawler creates a new instance of Crawler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCrawler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Crawler {
	mock := &Crawler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
