image: gos16052/crawl-data-slack

imageTag: latest

namespace: ""

cronJobs:
- jobName: "hackernews"
  command: "/go/bin/crawl-data-slack crawl hackernews --channel hacker-news --point_threshold 100"
  schedule: "0/30 * * * *"
  concurrencyPolicy: "Forbid"
  backoffLimit: 0
  restartPolicy: "Never"
  chromeEnabled: True
  env:
    SLACK_BOT_TOKEN: ""
    MYSQL_CONN: ""

chromedp:
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
