package lottecinema

// generated by https://mholt.github.io/json-to-go/
type Response struct {
	PlaySeqsHeader map[string]interface{}
	PlaySeqs       struct {
		Items     []Item `json:"Items"`
		ItemCount int    `json:"ItemCount"`
	} `json:"PlaySeqs"`
	IsOK          string      `json:"IsOK"`
	ResultMessage string      `json:"ResultMessage"`
	ResultCode    interface{} `json:"ResultCode"`
	EventResultYn interface{} `json:"EventResultYn"`
}

type Item struct {
	CinemaNameKR              string      `json:"CinemaNameKR"`
	CinemaNameUS              string      `json:"CinemaNameUS"`
	MovieNameKR               string      `json:"MovieNameKR"`
	MovieNameUS               string      `json:"MovieNameUS"`
	ViewGradeCode             int         `json:"ViewGradeCode"`
	ViewGradeNameKR           string      `json:"ViewGradeNameKR"`
	ViewGradeNameUS           string      `json:"ViewGradeNameUS"`
	FilmCode                  int         `json:"FilmCode"`
	FilmNameKR                string      `json:"FilmNameKR"`
	FilmNameUS                string      `json:"FilmNameUS"`
	SoundTypeCode             int         `json:"SoundTypeCode"`
	SoundTypeNameKR           string      `json:"SoundTypeNameKR"`
	SoundTypeNameUS           string      `json:"SoundTypeNameUS"`
	FourDTypeCode             int         `json:"FourDTypeCode"`
	FourDTypeNameKR           interface{} `json:"FourDTypeNameKR"`
	FourDTypeNameUS           interface{} `json:"FourDTypeNameUS"`
	TranslationDivisionCode   int         `json:"TranslationDivisionCode"`
	TranslationDivisionNameKR interface{} `json:"TranslationDivisionNameKR"`
	TranslationDivisionNameUS interface{} `json:"TranslationDivisionNameUS"`
	AccompanyTypeCode         int         `json:"AccompanyTypeCode"`
	AccompanyTypeNameKR       string      `json:"AccompanyTypeNameKR"`
	AccompanyTypeNameUS       string      `json:"AccompanyTypeNameUS"`
	AccompanyTypeShortName    interface{} `json:"AccompanyTypeShortName"`
	ScreenDivisionCode        int         `json:"ScreenDivisionCode"`
	ScreenDivisionNameKR      string      `json:"ScreenDivisionNameKR"`
	ScreenDivisionNameUS      string      `json:"ScreenDivisionNameUS"`
	IsBookingYN               string      `json:"IsBookingYN"`
	BookingSortSequence       interface{} `json:"BookingSortSequence"`
	CinemaSortSequence        interface{} `json:"CinemaSortSequence"`
	MessageYN                 string      `json:"MessageYN"`
	PlayDayKR                 string      `json:"PlayDayKR"`
	PlayDayUS                 string      `json:"PlayDayUS"`
	WarnigTimeFlg             string      `json:"WarnigTimeFlg"`
	WarnigTime                string      `json:"WarnigTime"`
	BrandYN                   string      `json:"BrandYN"`
	BrandNmKR                 string      `json:"BrandNm_KR"`
	BrandNmUS                 string      `json:"BrandNm_US"`
	BrandImageURL             interface{} `json:"BrandImageURL"`
	ScreenDesc                string      `json:"ScreenDesc"`
	StrtTimeCompare           interface{} `json:"StrtTimeCompare"`
	PosterURL                 string      `json:"PosterURL"`
	ScreenFloor               string      `json:"ScreenFloor"`
	NameSortSequence          interface{} `json:"NameSortSequence"`
	ScreenDivisionCodeReal    int         `json:"ScreenDivisionCodeReal"`
	ScreenNo                  int         `json:"ScreenNo"`
	SeniorCount               int         `json:"SeniorCount"`
	DisabledCount             int         `json:"DisabledCount"`
	CinemaID                  int         `json:"CinemaID"`
	RepresentationMovieCode   string      `json:"RepresentationMovieCode"`
	MovieCode                 string      `json:"MovieCode"`
	PlayDt                    string      `json:"PlayDt"`
	ScreenID                  int         `json:"ScreenID"`
	PlaySequence              int         `json:"PlaySequence"`
	StartTime                 string      `json:"StartTime"`
	EndTime                   string      `json:"EndTime"`
	TotalSeatCount            int         `json:"TotalSeatCount"`
	BookingSeatCount          int         `json:"BookingSeatCount"`
	SequenceNoGroupCode       int         `json:"SequenceNoGroupCode"`
	SequenceNoGroupNameKR     string      `json:"SequenceNoGroupNameKR"`
	SequenceNoGroupNameUS     string      `json:"SequenceNoGroupNameUS"`
	ScreenNameKR              string      `json:"ScreenNameKR"`
	ScreenNameUS              string      `json:"ScreenNameUS"`
	WeekendDivisionCode       int         `json:"WeekendDivisionCode"`
}
